# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# iOS build configurations 
appcenter_key = "8d50119554913b91a001fb00f4706e311ededc79"
appcenter_owner = "fcoskuncakir-gmail.com"
appcenter_appname = "CICDOKR"
ipa_path = "/Users/faik.cakir/Desktop/CICDOKR/builds/CICDOKR.ipa"
ios_app_scheme = "CICDOKR"
ios_export_method = "ad-hoc"

platform :ios do
  desc "Build, and push a release to AppCenter"

 lane :appcenter_release do
  build
  run_app_tests
  appcenter_upload(
   api_token: appcenter_key,
   owner_name: appcenter_owner,
   app_name: appcenter_appname,
   file: ipa_path,
   notify_testers: true,
   destinations: '*'
  )
  clean_build_artifacts
 end

 lane :build do
  gym(
  scheme: ios_app_scheme, 
  clean: true,
  export_method: ios_export_method,
  output_directory: '/Users/faik.cakir/Desktop/CICDOKR/builds',
  xcargs: "-allowProvisioningUpdates"
  )
 end

 lane :run_app_tests do
   scan(
     scheme: ios_app_scheme,
     clean: true,
     output_directory: "test_results",
     devices: ["iPhone 14"],
     code_coverage: true
   )
 end

end
